// src/app/layout.tsx
'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Provider } from 'react-redux';
import store, { persistor } from '@/store/store';
import { PersistGate } from 'redux-persist/integration/react';
import { Layout} from 'antd';  
import React, { useEffect, useState } from "react";
import AppHeader from "@/components/Layout/Header";
import AppFooter from "@/components/Layout/Footer";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Hospital System",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
   

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
                <AntdRegistry>
                <Layout className="layout" style={{ minHeight: '100vh' }}>
                    <AppHeader />
                        {children}
                        <AppFooter />
                        </Layout>
                </AntdRegistry>
            </PersistGate>
        </Provider>
        </body>
        </html>
    );
}